import React, { useRef } from 'react';
import { Editor as TinyMCEEditor } from '@tinymce/tinymce-react';

const Editor = ({ value, onChange }) => {
  // You can add TinyMCE plugins and configuration here if needed
  const editorRef = useRef(null);

  // Simulate AI content generation (replace with real API call)
  const handleGenerateAI = () => {
    const aiContent = 'This content was generated by AI.';
    editorRef.current?.insertContent(aiContent);
  };

  return (
    <TinyMCEEditor
      apiKey="lr517sywoeyu3m8oui2nykf4dxhz0f86mlxhanfmpj2bd99m"
      value={value} // Bind the value to the parent state (postContent)
      init={{
        plugins: 'emoticons',
        toolbar: 'bold italic emoticons',
        menubar: false,
        height: 250,
        statusbar: false, // Removes the status bar at the bottom
        branding: false,  // Removes the "Build with" branding
        content_style: `
          body { 
            color:#882AFF; 
          }
        `,
        // Adding custom AI button
        setup: (editor) => {
          editor.ui.registry.addButton('generate_ai_button', {
            text: 'Generate with AI',
            onAction: () => {
              handleGenerateAI();
            },
          });
        },
      }}
      onEditorChange={(content, editor) => {
        // Decode HTML entities to prevent displaying &amp; as "amp"
        const decodedContent = content
          .replace(/&amp;/g, '&')
          .replace(/&lt;/g, '<')
          .replace(/&gt;/g, '>')
          .replace(/&quot;/g, '"')
          .replace(/&#39;/g, "'");
        onChange(decodedContent); // Pass the decoded content to the parent component
      }}
      
    />
  );
};

export default Editor;
